### ISSUE TITLE
Memleak on SIGHUP

### ISSUE THREAD

**Issue by qnet-herwin** [FreeRADIUS/freeradius-server#1031]
Reproduced on a 32-bit linux system (both Debian and Ubuntu) with 3.0.x, also exists in older 3.0 releases, haven't tested with 3.1.x

The behaviour is best visible when running `atop` in Memory screen, and running `killall -HUP radiusd; sleep 1` in a loop. The atop screen looksl ike this:

```
  PID MINFLT MAJFLT VSTEXT  VSIZE  RSIZE   VGROW  RGROW RUID     EUID      MEM CMD
 4303    284      0   437K 73544K 28656K    660K   708K herwin   herwin     0% radiusd
```

In this case the growth is relatively small because the server is completely idle, but we've seen growth of multiple megabytes per SIGHUP in busy servers. The allocated memory is never freed again, the process just keeps on growing.

**Comment by alandekok** [comment]
The server tracks a lot of different data structures.  On HUP, the entire config is read again, all of the modules are re-loaded, and all of the modules are re-initialized.

Since the *old* config and modules are still in use, they are kept around for max_request_time*4.  If they were freed immediately, the server would crash, because requests are using the old data structures.

Try doing HUPs every 30 seconds.  You should see the memory freed after a while.

The best way to avoid these issues is to not HUP it every second.  Perhaps the HUP code could be updated to note that the config files haven't changed, and then refuse to do anything.

**Comment by alandekok** [comment]
I've pushed changes which makes it re-load the config *only* if the config files have changed. This should help minimize the problem.

But realistically... HUP has been "sort of working" for years.  It's very difficult to get it working correctly.  So fixing this is a low priority.

**Comment by alandekok** [comment]
I'm going to close this as a known issue.  Not only it's known, it's (sadly) intended.  There aren't really any ways around it.  The server doesn't have a garbage collection, so it has to track memory manually.  Which means lazily cleaning up memory.

The fixes I put in today means that HUP is now much safer than it used to be.  In 99% of the cases, it will just re-open the log file.  For the rest of the time, yes, it will *keep* memory, but not leak it.
