### ISSUE TITLE
Basic design for distributed SSL cache

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#1181]
SSL Session caching
---------------------------

Proposal is to manage everything using the session-state list.  session resumption can be seen as extending the original session, so in terms of architecture I think this works well.

There are a few key questions we need to answer

During SSL negotiation, when do we learn if a session should be resumed and the ID of the session?
---------------------------
If we learn the session ID in a callback function for getting the session data then we'll need a virtual server to get the data.

If we learn the session ID and then need to send more EAP data back to the client, before the OpenSSL attempts to read the cache, then we can avoid the virtual server, and just check for the existence of the Resumed-Session-Id attribute after each call to the EAP module.

Do certificates get cached too?
---------------------------
If they do, we need to make the same certificate attributes accessible as during the original EAP authentication attempt.

If they don't, we need to cache all the attributes derived from certificate fields too.

Should there be a 'add to cache' virtual server
---------------------------
Do we need a special virtual server for caching the SSL blobs?

Can we control any fields that get sent to the client, or any components of the session id
---------------------------
We only need a byte's worth of information, but it could be useful for figuring out *where* the session is cached.

In a two site scenario, where the slaves are located at the alternate site, and a site goes offline, the remaining site knows to query the masters at its site, or the slaves at its site.

If it has no hint where the session is located, it has to query both.

![overview_diagram](https://cloud.githubusercontent.com/assets/791758/9075182/c8baf328-3adf-11e5-82ac-73abd976eb80.png)

**Comment by alandekok** [comment]
We learn that a session was resumed about when we send a TLS Success. See src/main/tls.c, tls_success().  That is where we save the RADIUS attributes on the first session, and restore them on subsequent ones.  This is for the internal cache of attributes which are associated with an SSL session.  The association is managed by OpenSSL, not by us.

That cache is an in-application cache, which doesn't do save/restore of sessions.  That is the next bit.

There is *also* the SSL code to do session resumption, with its associated callbacks.

* `cblts_remove_session()` is a called by OpenSSL to remove a session from an external cache.
* `cbtls_new_session()` is called by OpenSSL when a new session is created.  It is supposed to save the SSL data, and any RADIUS attributes in an external cache.
* `cbtls_get_session()` is called by OpenSSL to get a session from the external cache.

These functions are set as callbacks when a TLS context is created:

			SSL_CTX_sess_set_new_cb(ctx, cbtls_new_session);
			SSL_CTX_sess_set_get_cb(ctx, cbtls_get_session);
			SSL_CTX_sess_set_remove_cb(ctx, cbtls_remove_session);

They get called with arguments "char *data, size_t len", which is a binary blob containing a key to the SSL session.

# Proposal

My suggestion is to write *new* callbacks, which won't affect the existing ones.  Because the functions are callbacks, they can't be processed as part of processing the current REQUEST.  They have to be processed through a new virtual server.

## What to do

We will need to do the following:

* create a new virtual server to process the SSL session cache
* it should only contain an "authorize" section
* the *current* REQUEST packet should be run through it
* the REQUEST should be updated to contain a control list of the SSL session key from above, and a new attribute indicating the desired action (read / write / delete)

For delete, the session indicated by the key should be deleted.  There is no real way to deal with "delete failed", so the return code of the virtual server is ignored.

For write, the virtual server will write any request / reply / session-state attributes it deems useful.  It should also mark the cache entry with a creation and expiry time.

For read, the virtual server will update any request / reply / session-state attributes it deems useful.

Once that virtual server has finished processing, the current request will be deemed to be updated, and will continue to be processed through the rest of the current virtual server, as is done now.

## Implementation

It should require some new configuration:

* the name of a virtual server to use for caching
* 3 callbacks which save the current virtual server, call the new one, and do the various OpenSSL magic to update the SSL crap
* some Unlang code to save / restore / delete entries from a cache.

# Issues

The idea of yet another virtual server is annoying.  Especially because we're overloading the "authorize" section yet again.  It would be *much* more preferable to have Unlang blocks which are named for what's actually happening.  e.g.

    server tls_cache {
      cache read {
        ...
      }
    
      cache write {
        ...
      }
    
      cache delete {
        ....
      }
    }

The problem with that is gluing everything together.  We would like to compile those blocks as ??? Maybe "authorize" sections ??? And do so automatically.  Ideally, have some way of signalling from the EAP / TLS module to the main Unlang parser / compiler, that this parsing needs to be done.

And then the debug output would have to be changed, too.  So that we would see "Executing cache read", and not "Executing authorize".  That seems simple to change, tho.  Just cache the original name from the CONF_SECTION, instead of dereferencing `section_type_value[comp].section`, which are hard-coded to "authorize", etc.

It might be simpler just to hack the parser to treat "cache" as a synonym for "authorize".  And "cache read" as defining "Autz-Type cache_read".  It's fugly, but it makes things a LOT easier to understand for the administrator.

**Comment by arr2036** [comment]
All that seems reasonable.  I think the way that's most consistent with the server is to set Autz-Type and run different authorize sections.  I'm not sure there's any advantage to naming the authorize section 'cache', just leave it as authorize, then it's clear the behaviour is the same.

Creating synonyms or aliases for sections was something proposed for when the send/recv code was introduced.  There's probably not a whole lot of point hacking something different together now for it.

**Comment by arr2036** [comment]
Regarding the separate callbacks it would be good to remove the old caching code at some point before v3.1.x is released.  Requiring an external process to cleanup old cache entries is poor.

We can do a much better job with a new rlm_cache driver.  The one I had started writing shadowed the entries in an rbtree, as well as writing them to disk.  On startup it read all the cache entries back into the rbtree, and unlinked any files associated with expired entries.  As rbtree entries expired during normal cache operation, the counterpart files on disk were also unlinked.

**Comment by alandekok** [comment]
We can only have one "authorize" section.  The Autz-Type blocks have to be sub-sections of that...

**Comment by arr2036** [comment]
If we're being pedantic multiple sections within the authorize section.

```
authorize {
	Autz-Type cache_read {

	}
	Autz-Type cache_write {

	}
	Autz-Type cache_delete {
	}
}
```

**Comment by arr2036** [comment]
I've documented the functions you've added, and fixed ones where the return type was bool (we agreed to use int in new code). Also renamed ``get_session_key`` verb order was wrong, and it didn't really describe what it was doing, it's now ``cache_key_add`` feel free to change it again to something more descriptive.

``cache_process`` now returns a failure code, but the only effect of a failure is to stop processing early and to emit warnings.

There's an issue with the code that adds ``PW_TLS_SESSION_CACHE_ACTION``.  It never deletes existing instances of the attribute meaning ``&control:TLS-Session-Cache-Action`` will contain the first cache action that was executed.  That may be an issue if the virtual server is called to retrieve and then delete a cache entry.

It's not clear whether the final iteration of the code will use ``Autz-Type`` or ``TLS-Session-Cache-Action``, so i'll leave that for you to fix.

**Comment by alandekok** [comment]
That looks OK.  I've added code to delete the attributes before they're added, and to delete them after they're used.

The functions are hard-coded to use `Autz-Type Cache-Foo`.  BUT they also set `TLS-Session-Cache-Action`, just in case anyone cares / needs.

**Comment by arr2036** [comment]
Ok, makes sense.  One thing that would be nice is for the validity period of the session to be included (so it can be assigned to Cache-TTL), I don't know if there's a way to extract that from the SSL_SESSION struct?

Other than that is there anything else apart from testing?

**Comment by alandekok** [comment]
I don't think there's a validity period for the SSL_SESSION struct.  It's just data.

I think we're done with this issue.
