### ISSUE TITLE
Regular expression match in rlm_sql fails in 3.0.8

### ISSUE THREAD

**Issue by derde** [FreeRADIUS/freeradius-server#1205]
In freeradius 2, the operator "=~" in the radcheck table (authcheck_table) can be used for regular expression matches, with the "Value" column being interpreted as a regular expression, and matched against the attribute.  This allowed matching multiple permitted attribute values, for example with expressions like Calling-Station-Id =~ 5551234|5554321

This function seems to have been broken in freeradius 3 (possibly with changes in quoting between strings and regular expressions).  The operator is treated as a string match instead of a regular expression.

**Comment by jpereira** [comment]
@derde Please, try using the latest version. 3.0.8 is completely out of date.

**Comment by arr2036** [comment]
@jpereira the code path is very similar to what radsniff should be using for regexes, and someone else (maybe @derde?) just reporting something on the list.  So i'm guessing there's something wrong with paircmp regexes.

**Comment by derde** [comment]
@jpereira - no change.  After installing 3.0.9 (with its strange new interest in openssl version numbers, and its need to see net-snmp available) there is no change to the handling of regular expressions, which agrees with the changelog's silence on the matter.

**Comment by arr2036** [comment]
It's not strange, it's sensible, and there's no requirement for net-snmp.

**Comment by alandekok** [comment]
> After installing 3.0.9 (with its strange new interest in openssl version numbers

This is called "security".  A few OpenSSL versions are insecure.  We don't let you use them by default.  Also, OpenSSL has a habit of breaking binary compatibility.  Which meant that upgrading OpenSSL could cause radiusd to crash, and people would blame radiusd.  When it was really OpenSSL.

I am amazed at the fanatical dedication people have to blaming FreeRADIUS for everything.  FreeRADIUS isn't an OS.  It isn't a GUI.  It isn't an SSL library.  It isn't a database.

It does RADIUS.  If something ELSE goes wrong in a system,. blame SOMETHING ELSE.

As for the "users" file changes, yes, this is how v3 works.  Use "unlang" instead of the "users" file.

Or, submit patches which make the "users" file support regexes.
