### ISSUE TITLE
xlat/switch with multiple cases

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/freeradius-server#1324]
Hi @alandekok,

I have discussed with @arr2036 about the support for multiple cases in xlat/switch.

e.g:

```
switch &avp {
    case A
    case B
    case C {
        do_something
    }

    case {
        do_default
    } 
}
```

I think that could be nice to avoid multiple statements.

**Comment by alandekok** [comment]
That's hard... the parser isn't smart enough to do that.  And making the parser smarter is hard, because the parser is dumb.  Very, very, very, very, dumb.

It would be better / easier to do something likeL

    case A,B,C,D {
    
    }

But even that would take a bit of work.

**Comment by jpereira** [comment]
for me ok, I agree with this idea. What do you think @arr2036 ?

**Comment by jpereira** [comment]
@alandekok The parse need to be so smart about that!

```
case %{AVP}, ${macro}, "some string", "Caipirinha" {

}
```

**Comment by arr2036** [comment]
I think it's easier to add a CONFIG_PAIR subtype without an operator

**Comment by jpereira** [comment]
I believe that your idea could be nice! but, I can't figure out @arr2036 :(

**Comment by arr2036** [comment]
Need to teach the parser to accept ``foo bar`` and create a ``CONF_PAIR`` from it.

I think you're trying to do too much in unlang is its current form.  We've already got all the low hanging fruit in terms of ramming unlang into the v0.0.x parser.  It really needs a rewrite to do more fancy things.

As i've said many many times, if you moved to v3.1.x, i'd be far more willing to spend time on enhancements, and working with you.  If @alandekok was ok with it, we could start cutting <whatever> releases of v3.1.x to act as milestones/markers.  If it made a difference we could use the word stable e.g. ``stable0-v3.1.x``, ``stable1-v3.1.x``, they're just git tags, like the blessed releases are just git tags.

Adding enhancements to v3.0.x is detrimental to the project.  Even small changes can and do break things. v3.0.x needs to be as stable as possible now, so that package maintainers will keep up with the point releases, and so users feel confident using it in production settings.

**Comment by arr2036** [comment]
Also, versions numbers are a stupid, meaningless, and outdated concept.  I hate them, almost as much as I hate perl.

**Comment by alandekok** [comment]
If we're going to allow multiple `case` statements, or regex matches e.g. #1486 ... we might as well just allow the "case" statements to have conditions:

    case (a || b || c || d) {
        ...
    }

Which makes them entirely equivalent to "if" statements.

TBH, I'm inclined to close both this issue and #1486 as "nice, but not necessary".

**Comment by arr2036** [comment]
Case statements should be literals, and we should allow fall through.  The point of switch statements it to allow comparison of an attribute against multiple case statements.  I don't see how that could be done with multiple conditions.

Ideally switch statements would be optimised to use rbtrees for value lookups, especially as they're now the primary method of mapping realms to destination servers.

If users want regexes and fancy matching, then that can be cone in normal ``if elseif else`` blocks.

**Comment by arr2036** [comment]
The speed difference isn't so much from O(n) vs O(log n), but more from only needing to perform attribute resolution or xlat expansion once, instead of for each comparison.

**Comment by alandekok** [comment]
if case statements are literals, then they can't be regular expressions :(

**Comment by alandekok** [comment]
I think in the end we're not going to do this.  Changing the parser is hard.  If the syntax was closer to C, then adding multiple cases for one execution block would be easier.  But we're stuck with the current syntax, which uses `{ ... }` to control new execution blocks.
