### ISSUE TITLE
Different check intervals for zombie and dead

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#140]
RFC 2865 prevents us from sending keep-alives (including status-checks) during normal operation. The only time were actually allowed to check whether a server is up, is if we suspect it's down.

This is why home servers are marked as zombie, before being marked as dead, and that the lack of responses from a home server is the only thing that will cause FreeRADIUS to try to actively determine its state.

In proxy networks where the first hop is not the terminating server, the next hop server may sometimes be marked as offline if an upstream proxy goes offline, when this occurs we want to quickly determine whether the next hop is really offline or whether its the upstream server.

The num to alive, and check frequency should be low and high respectively for servers in zombie mode, as we have no reason to believe the server is actually offline. Once the server hasn't responded for a period, we can guess that the issue is with the server itself and at this point we want to use a higher num to alive (to stop spurious fail backs) and higher check interval, so were not flooding the network with 'ping' packets over a long period.

Currently the same configuration options are used for both, but ideally we should provide the option to configure them differently.

**Comment by alandekok** [comment]
It's probably best to not have these configurable.  Instead, just use the current timers for the "dead" period, and use 1/4 of them for the "zombie" period.

Or maybe just hard-code check_interval to "1" for zombie period, and leave everything else alone.

We should also skip the Status-Server checks during zombie_period, if we proxied a packet to the zombie home server in the last "check_interval" period.  i.e. if we proxy 1000 packets to it before deciding it's zombie, the NAS will retransmit some of those, meaning we don't need to send our own Status-Server packets.

Since zombie_period is short, it's acceptable to bug the hell out of the home server during that time.
