### ISSUE TITLE
Python modules do not receive configuration parameters

### ISSUE THREAD

**Issue by alejandro-perez** [FreeRADIUS/freeradius-server#1451]
There is no way to provide configuration parameters to python modules. This is inconvenient as it requires users to modify the python module script, that might be installed in a standard PYTHON PATH. Also it makes difficult to maintain configuration when a new version is installed.

I understand that the dynamic nature of python vs. the static nature of the FR configuration conflict, but a trade-off solution should be provided. Here is my suggestion:
* Add a new configuration parameter to the rlm_python module, called "module_configuration". This is a string.
* Make this string somehow available to the python module (perhaps as a module constant). The format of this parameter is not standardize, so one python module might use CSV, whereas other might use JSON.

**Comment by alejandro-perez** [comment]
In case you are wondering, yes I have a tentative patch :)
```
diff --git a/src/modules/rlm_python/rlm_python.c b/src/modules/rlm_python/rlm_python.c
index 22456a0..aadb0e1 100644
--- a/src/modules/rlm_python/rlm_python.c
+++ b/src/modules/rlm_python/rlm_python.c
@@ -58,6 +58,7 @@ typedef struct rlm_python_t {
 	void		*libpython;
 	PyThreadState	*main_thread_state;
 	char const	*python_path;
+	char const  *module_configuration;
 
 	struct py_function_def
 	instantiate,
@@ -102,6 +103,7 @@ static CONF_PARSER module_config[] = {
 #undef A
 
 	{ "python_path", FR_CONF_OFFSET(PW_TYPE_STRING, rlm_python_t, python_path), NULL },
+	{ "module_configuration", FR_CONF_OFFSET(PW_TYPE_STRING, rlm_python_t, module_configuration), NULL },
 	CONF_PARSER_TERMINATOR
 };
 
@@ -239,6 +241,14 @@ static int mod_init(rlm_python_t *inst)
 		}
 	}
 
+	/*
+     * add module configuration as a constant
+	 */
+	if ((PyModule_AddStringConstant(radiusd_module, "module_configuration",
+					     inst->module_configuration)) < 0){
+		goto failed;
+	}
+
 #ifdef HAVE_PTHREAD_H
 	PyThreadState_Swap(NULL);	/* We have to swap out the current thread else we get deadlocks */
 	PyEval_ReleaseLock();		/* Drop lock grabbed by InitThreads */
```

**Comment by jpereira** [comment]
Hi @alejandro-perez,

This is a good idea! I completed your suggestion here in #1453

**Comment by alejandro-perez** [comment]
Thanks! That was quick! :) Perhaps putting them in the module radiusd is not optimal, but I didn't know how to make it in the own module (e.g. mypythonmod)

**Comment by herwinw** [comment]
The `rlm_perl` module is a little more mature than `rlm_python` (just to be clear: I'm talking about the FreeRADIUS modules, not the languages) and has an option that is comparable to this feature, you could take a look at commit 7768e331cf1d6c07a2e2c4ad4b9e0153640ea757 for inspiration. The big advantage here is that it is not limited to a single value, but rather results in a hash (dict) of results, which could save the amounts of (de)serialization required in the proposed patch here (I believe it even can parse sections within sections nowadays, but I'm not sure about that)

**Comment by alejandro-perez** [comment]
That would be even better, since I'm doing JSON parsing and having a dict nonetheless. Is there any way you could copy this functionality within python module?

**Comment by herwinw** [comment]
I'll try to have a look at it this weekend, but I'm not promising anything (and I have hardly any experience with python, let alone with using python from C).

To view it a little bit broader: we currently have three embedded language modules: `rlm_perl` which is pretty mature and usable, `rlm_python` which is far inferior, and `rlm_ruby` which I have never gotten to compile. Maybe it's a good idea to get the ways of using these languages a little bit more in sync, and maybe get them to share some common code like parsing the extra configuration (what is what this ticket started). The way they work is a bit random now (perl uses global hashes for all the key-value stores, I believe python passes the request store as a parameter of type dict to the functions, and I believe ruby does the same as python (except that it calls this data structure a hash instead of a dict)), maybe that should be synchronized too. That woul mean a change that is all but backwards compatible, thus 3.1 only. But I'm getting offtopic, if I can write a proposal for change this weekend I'll take that to the mailing list to discuss it there.

**Comment by arr2036** [comment]
rlm_ruby needs to be rewritten with mruby.

**Comment by alejandro-perez** [comment]
Obviously, that would be the best way to proceed, as all these 
meta-modules need a way to provided specific per inner-module 
configuration parameters (that is what the python module was missing). 
If the code can be shared, even better.

**Comment by arr2036** [comment]
Closing this as it's addressed in @herwinw's patch
