### ISSUE TITLE
(Debian) kernel upgrade breaks freeradius EAP-TLS / 802.1x

### ISSUE THREAD

**Issue by sebastianw** [FreeRADIUS/freeradius-server#1468]
After upgrading the kernel package on one of our radius servers we noticed that Windows clients could no longer authenticate trough EAP-TLS (WiFi) or 802.1x (wired). It seems that after the upgrade freeradius no longer processes large fragmented UDP packets, in our case Access-Request packets with a length of 1686 bytes.

We tested with these kernel versions:

Affected:
linux-image-3.16.0-4-amd64 3.16.7-ckt20-1+deb8u1
linux-image-3.2.0-4-rt-amd64 3.2.73-2

Not affected:
linux-image-3.2.0-4-rt-amd64  3.2.71-2

This is also tracked in the Debian BTS, currently in two separate bugs for [freeradius](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808293)  and [src:linux](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808374).

I'm not sure if the problem must be fixed in freeradius or in the kernel so I'm adding this issue here as well as commenting the bugs in the Debian BTS.

**Comment by arr2036** [comment]
There's very little we can do, unless they've introduced a magic socket option that now needs to be applied to enable receipt of fragmented UDP packets.

**Comment by alandekok** [comment]
Note that we set IP_DONTFRAG.  But that *should* apply only for outgoing packets.

**Comment by arr2036** [comment]
Yes, assuming @sebastianw verified the server really wasn't receiving fragmented frames, and was not receiving but failing to respond to fragmented UDP frames, and that the EAP MTU was set correctly.

**Comment by sebastianw** [comment]
I'm not sure if I understood correctly so I'm trying to rephrase what I see. :) The server gets a fragmented UDP packet (2 fragments). With the "older" kernel freeradius does receive/process that packet and with the newer kernel it doesn't. If I understood correctly there is no other way for you to get the packet from the kernel so the kernel is at fault for not providing the packet data, right?

**Comment by alandekok** [comment]
IP packet fragmentation and re-assembly is the responsibility of the kernel.  If fragmented packets aren't reaching an application like FreeRADIUS, it's because the kernel isn't delivering them.

That being said... it may be the IP_DONTFRAG option.  The kernel may *think* it's been asked to not deliver fragmented packets.

Either way, I think it's a kernel bug.

**Comment by qnet-herwin** [comment]
As mentioned on the mailing list today (http://lists.freeradius.org/pipermail/freeradius-users/2016-January/081486.html): this should be fixed in todays updates. Upstream ticket is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808293.

@sebastianw Have you had a chance to try it again with a shiny new kernel?

**Comment by alandekok** [comment]
I'll close this.  The upstream comment indicates it was a kernel bug.
