### ISSUE TITLE
debian build 3.0.11 logrotate.d  why still radius

### ISSUE THREAD

**Issue by whyname** [FreeRADIUS/freeradius-server#1510]
debian build 3.0.11 logrotate.d  why still radius not freeradius, i found in debian file this is fixed, why build not auto fix?

**Comment by alandekok** [comment]
Please say *which* file is wrong, and what is wrong with it.

If you have general questions about FreeRADIUS, they belong on the freeradius-users mailing list.

**Comment by matsimon** [comment]
I think I found the issue... took me some reading about Debian packaging details:

 * `debian/patches/logrotate-path.diff` correctly patches `scripts/logrotate/freeradius`, I do see the patch getting applied when building the package without errors on both 3.0.x and 3.1.x
 * However the file that gets eventually installed is the one with the content of `debian/freeradius.logrotate` which is set to rotate files `/var/log/radius`, not `/var/log/freeradius`

It looks like the patched is never going to be installed since [dh_installlogrotate](http://manpages.ubuntu.com/manpages/hardy/man1/dh_installlogrotate.1.html) in `debian/rules` will always install freeeradius.logrotate to `/etc/logrotate.d`

So yes, @whyname is right about the fact there is an issue with logrotate on Debian, but I agree with @alandekok that the description doesn't contain enough details.

I'd propose the following path to fix this issue similar to what the Red Hat packaging does (it also uses `redhat/freeradius-logrotate`).

* Drop `debian/patches/logrotate-path.diff`
* Update copy `scripts/logrotate/freeradius` to `debian/freeradius.logrotate` and apply the fixes we previously had in the patch for Debian.

I haven't found an example where dh_installlogrotate was used to with `--name=` pointing to a file outside of the `/debian` folder that's why I propse this solution for a fix.

Looking forward to your feedback so I can go forward and prepare pull requests.

**Comment by matsimon** [comment]
Once this issue is fixed I'll likely cherry-pick that fix the the 3.0.11 release packages to my Debian (1Labs) repository. Actually this might be of interest to @fajarnugraha as well who uploads to the Ubuntu PPA.

**Comment by alandekok** [comment]
sounds good to me.

**Comment by fajarnugraha** [comment]
Thanks @alandekok and @matsimon , ppa:freeradius/stable-3.0 updated with df0be79
