### ISSUE TITLE
LDAP-Group et al need to trigger a load of rlm_ldap

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#1642]
# Issue type
-  [x ] Defect - Unexpected behaviour (obvious or verified by project member).

# Defect/Feature description
## How to reproduce issue
Use LDAP-Group in a condition, without listing ldap anywhere in the server.

## Technical issue
Because the ldap module is not listed anywhere its bootstrap method is never executed.

## Resolution
There's a few ways that this could be resolved.

The easiest would be to always run bootstrap for every module, so the pair comparisons are registered, and then add instantiation callbacks for paircmps,  as we do with xlats and maps already.

Then a paircmp is instantiated it could trigger full instantiation of the module.

Another way would be to add proper functions and remove paircmps completely.

**Comment by mcnewton** [comment]
`LDAP-Group` has been removed from the dictionaries in 3.0 as well (2293292d).

If I start v3.0.x up here referring to `LDAP-Group` in unlang, but not instantiating `ldap` anywhere, the server stops with `"Unknown attribute 'LDAP-Group'"`, which seems like desired behaviour to me?

Or are you saying it's the other way around: that because `LDAP-Group` has been used in unlang, that should trigger rlm_ldap to be instantiated?

**Comment by arr2036** [comment]
Exactly, if something uses LDAP-Group then the server should instantiate LDAP.

I guess we have the same problem with xlats and maps actually...

**Comment by mcnewton** [comment]
Not sure how this can be an issue. If `mods-enabled/ldap` exists, then `ldap` is instantiated with that config, and `LDAP-Group` will work fine.

If it hasn't been instantiated, then there is no config. So `LDAP-Group` is meaningless because even if you called bootstrap there would be no ldap server configuration to use, so it wouldn't know what to do.

Or am I missing something?

**Comment by mcnewton** [comment]
Hmm. does rlm_ldap get instantiated with `mods-enabled/ldap` in place, but no call to `ldap` in `sites-enabled/*`? Guess that's possible.

**Comment by arr2036** [comment]
Not sure.  I thought it didn't.

**Comment by mcnewton** [comment]
No, you're right. Config in `mods-enabled/ldap` doesn't instantiate it - needs to be in `instantiate {}` or used in `authorize` etc.

**Comment by arr2036** [comment]
So now we have bootstrap, it seems like it might be worth just running the bootstrap method, registering maps/xlats/paircmps.  Then if the ever get used anywhere, complete the instantiation and actually open outbound connections.

If they don't, we could unload the modules and free up the memory.

The modules *should* be OK to be freed after running just the bootstrap method, because the free method should assume that module instantiation can error out at any point.

**Comment by alandekok** [comment]
I confess to being confused by this issue.

If FOO-Group is used, should the server automatically find (somehow) module "foo" and load it?  If so, why?  How does it find the module?

And if the module isn't listed in `mods-enabled`, why would the server load the module?

This all seems utterly magical to me.

What may be useful is to check if a module is used, and if not, remove it from the list of enabled modules.  But doing that involves:

* adding a `referenced` field in the `module_instance_t` with initial value `false`.
* marking `referenced = true` if the module is listed in a virtual server
* marking  `referenced = true` the "pass2" code in `modules.c`, when the module is referenced from an xlat
* marking  `referenced = true` the "pass2" code in `modules.c`, when the module is referenced from a paircompare
* looping over all loaded module instances, looking for (and complaining) if we find a loaded module with `referenced = false`.

Honestly, I just don't see the effort as being worth it.  If people are too lazy to notice that they enabled `ldap` but aren't using it, they can pay the price of the server using a tiny bit extra bit of memory at run time.

Unless someone comes up with a compelling reason for this, I just don't see a reason for any of it.

**Comment by mcnewton** [comment]
So to hit this you have to
 * create `mods-enabled/ldap` (or whatever module)
 * use `LDAP-Group` in `sites-enabled/default`, or similar
 * *not* call `ldap` in anywhere.

The current fix is to either call `ldap` from somewhere (which is what 99% of people already do, which is why this issue generally never crops up), or add `ldap` to the `instantiate{}` section in `radiusd.conf`.

If it really is an issue, why not just automatically instantiate all modules in the `modules{}` section (i.e. if you've added it to `mods-enabled`) and forget about the `instantiate{}` section altogether.

ISTR in the past there was a change (v2 era?) to *not* instantiate everything, but that was when modules were all listed in the `modules/` dir, so there was no way to distinguish whether they were used or not. Now there is separate mods-available/enabled, is is worth worrying about?

Can then just drop the `instantiate{}` section from the config as well, which simplifies things.

**Comment by arr2036** [comment]
instantiation still needed to create named redundant/load balance sections

**Comment by mcnewton** [comment]
Can't that just be done as a policy instead? Or is that less efficient?

And the other reason for is - getting the module ordering right - can just be done (more clearly) by renaming symlinks in `mods-enabled`, if required.

**Comment by alandekok** [comment]
It isn't possible to look at the server internals in unlang.

In term of module ordering, the `instantiate` section is good enough.  If we want to pull that section out of `radiusd.conf`, we could just have a `raddb/mods-enabled/instantiate` configuration which is loaded first, and just put the `instantiate` section there.

**Comment by wanggaolin** [comment]
i usage openldap auth,error message:

(8) suffix: No '@' in User-Name = "t1", looking up realm NULL
(8) mschap: ERROR: FAILED: No NT/LM-Password.  Cannot perform authentication
(8) mschap: ERROR: MS-CHAP2-Response is incorrect
(8)   MS-CHAP-Error = "\010E=691 R=1 C=c8e50c3ee3fb4b3c951f17252099f261 V=3 M=Authentication failed"
(8) eap_peap:   MS-CHAP-Error = "\010E=691 R=1 C=c8e50c3ee3fb4b3c951f17252099f261 V=3 M=Authentication failed"
(8) eap_peap:   MS-CHAP-Error = "\010E=691 R=1 C=c8e50c3ee3fb4b3c951f17252099f261 V=3 M=Authentication failed"
(9)   User-Name = "t1"
(9) suffix: No '@' in User-Name = "t1", looking up realm NULL
(9) eap: ERROR: Failed continuing EAP PEAP (25) session.  EAP sub-module failed

How can I solve it?
