### ISSUE TITLE
Implement async rlm_sql and drivers

### ISSUE THREAD

**Issue by arr2036** [FreeRADIUS/freeradius-server#1913]
Need to verify which SQL backends offer access to the FD and provide support async querying.

**Comment by arr2036** [comment]
@pwdng investigated.

## The Good
- PostgreSQL has full, native async I/O support
  - https://www.postgresql.org/docs/9.6/static/libpq-async.html
- The original MySQL client driver does not support async connections, but the Maria DB client does, and is likely protocol compatible.
  - https://mariadb.com/kb/en/mariadb/non-blocking-api-reference/
  - https://github.com/chkpk/mysql-async-example/blob/master/mysql_async_example.c
- Oracle Instaclient also has async I/O support
- ODBC support is dependent on the connector.

## The Bad
- Firebird (we can drop this as firebird provides an ODBC interface).
- FreeTDS (we probably need to keep this).
- DB2 (very small number of users, can probably drop this).
- SQLite (we need to keep this)

**Comment by alandekok** [comment]
My $0.02 is to create an rlm_sql_async, and go from there.  The idea is that we can then prune it down to (e.g.) Postgres, and work on that code / API.  Once that's done, add MySQL, etc.

We're probably OK with SQLite mostly as-is.  File IO is blocking, but there isn't much you can do about that.  And SQLite has file locking primitives so that only one thread at a time is accessing the DB.

**Comment by arr2036** [comment]
Just need to markup that rlm_sql instance as blocking when we're either running with a blocking ODBC driver, or using FreeTDS or SQLite.

That means we can pass it off those calls to the blocking I/O threads or however we end up doing that.

Regarding copying the code.  We could do.  I think @pwdng is reviewing the code, so i guess it depends on whether there's breaking changes required.

**Comment by pwdng** [comment]
For ODBC & Oracle, it turns out the only non blocking option available is to use polling.
With previous versions of Oracle, it was possible to get the underlying file descriptor but this doesn't seem to be the case anymore and they don't recommend using the non blocking API anymore as polling is bad.
As for ODBC, there is a notification based system but it isn't available in either iODBC or UnixODBC. The remaining option here is to use polling for non blocking calls.

So true event driven non blocking will only be available for Postgres & MySQL.

**Comment by pwdng** [comment]
Both MySQL and Postgres can only handle a single concurrent request per connection to the DB.
The initial thought of having a single connection per worker thread is therefore impossible.
We therefore need to keep a connection pool.

We can probably stick to a similar architecture to what's been done for rlm_rest and have a pool per thread.

**Comment by arr2036** [comment]
Sure, that's simple enough.  Looks like it is worth writing that two tiered connection pool stuff, i'll see if I can find time tomorrow.

**Comment by pwdng** [comment]
Here's ongoing work to make rlm_sql async.
https://github.com/pwdng/freeradius-server/commits/async_sql

Ignore changes to postgres driver.
Goal here is to make the module compatible with non blocking drivers.
mod_authorize has been migrated.

**Comment by pwdng** [comment]
I have made some changes to my original commit and broken it up a bit to make it more readable.

**Comment by pwdng** [comment]
See PR https://github.com/FreeRADIUS/freeradius-server/pull/1940

**Comment by ndptech** [comment]
All SQL drivers are now using trunks rather than connection pools and those that have some form of async behaviour are using it:
  - MySQL / MariaDB - event driven
  - PostgreSQL - event driven
  - Oracle - polled
  - unixodbc -polled
  - Cassandra - polled
