### ISSUE TITLE
ORACLE: TO_DATE in queries creating errors in SQL

### ISSUE THREAD

**Issue by ibaguio** [FreeRADIUS/freeradius-server#1934]
On freeradius **3.0.13**, queries for **rlm_sql_oracle** raises an exception with Oracle if it includes the TO_DATE function

    ORA-01830: date format picture ends before converting entire input string

further investigation shows that this is caused by the update on how 3.0.13 prints its timestamp ("%S") on the SQL query, which includes the milliseconds, whereas checking on 3.0.12, the milliseconds is omitted.

    TO_DATE('2017-03-08 15:30:00.000000', 'yyyy-mm-dd hh24:mi:ss')    # 3.0.13
    TO_DATE('2017-03-08 15:30:00', 'yyyy-mm-dd hh24:mi:ss')           # 3.0.12

Oracle's **TO_DATE** function raises an exception whenever milliseconds are included.

**Comment by arr2036** [comment]
Column type should be switched to timestamp and to_timestamp should be used.

**Comment by alandekok** [comment]
We shouldn't have behavior changes in a minor release.  I'll push a fix.

**Comment by geaaru** [comment]
Hi, sorry for reopen a discussion about this. This changes is relative to issue #1917 where on my commit it was already changes to '%T' and not '%S'. But I see only one thing: timestamp.tv_usec is a long field not a int (like is present on my patch). In this case is correct force a cast to int or could be best use a long instead of int  (row 2136 on release 3.0.14)? Thanks in advance for your comments.

**Comment by alandekok** [comment]
usec is microseconds, which is limited to 1,000,000.  Using an `int` is fine.
