### ISSUE TITLE
FreeRadius gets stuck infinitely if OCSP responder is alive but does not return any result

### ISSUE THREAD

**Issue by shayyo** [FreeRADIUS/freeradius-server#1962]
Scenario is as follows:
 
Came across this issue when my OCSP server went down (but still listened on port 80)
Scenario is as follows:
1. freeRadius is configured to check certificates' validity against an OCSP check responder
2. OCSP responder does listen on port 80 but does not return any results
3. An eap-tls supplicant authenticates to the network-->freeRadius tries to perform an OCSP check against the responder-->responder does listen on port 80 (and does not return any data)

Results, freeRadius instance is stuck waiting to the OCSP responder to return data.

**Comment by alanbuxey** [comment]
#
                        #  Number of seconds before giving up waiting for OCSP
                        #  response. 0 uses system default.
                        #
#                       timeout = 0


so....suggests the system default is long... how about changing this to a a few seconds longer than your OCSP ever takes - maybe eg 3 seconds?

**Comment by alandekok** [comment]
Configure the server as per the previous comment.

**Comment by shayyo** [comment]
Thanks,

In my first post I did not mention that I did go through that setting (timeout) with no success.
The problem occurs when the FreeRadius server opens a TCP socket towards the OCSP server but no OCSP-related traffic is returned.
In that case, the 'timeout' setting does not make any difference to the behavior of the FreeRadius server.

**Comment by alandekok** [comment]
The main issue is that the code in question is not FreeRADIUS.  We just use the OCSP API in OpenSSL.  So if that blocks, there's little we can do.

On top of that, the solution to the problem of "my OCSP server is down" is to not have the OCSP server go down.  Any patches to FreeRADIUS would just work around the probem.

**Comment by shayyo** [comment]
Fair enough

Thanks

**Comment by alanbuxey** [comment]
what you could do is  have a helper App on the server that checks the OCSP
server...and if theres a problem then update a flag in eg SQL, then,
with the help of some unlang....and probably some changes in the FR, people
could decide if to OCSP or not eg

if (%{sql:select ocsp.state = "1"}) {
     ocsp
 }

such a construct might be possible in FR 4 as, i believe, there will be
some changes so that there are new things for CRL and OCSP....eg if OCSP
fails then do a CRL etc...right now its all pretty much hardcoded behaviour
in current releases

but as Alan says, this is just papering over cracks

alan
