### ISSUE TITLE
Coa Not Working in pppoe 3.0.11

### ISSUE THREAD

**Issue by midobona** [FreeRADIUS/freeradius-server#2077]
Hello = (Salam Alikom)

I have a problem when updated coa pppoe version 3.0.11 but  in freeradius version 2.1.2 working but have many problem so i updated to 3.0.11 how i can solve this problem without lose this version 3.0.11 Iam using radclient comment to updated coa so i guess problem in radclient

Thanks ((Sorry For My Language English ^_^))

**Comment by alandekok** [comment]
Please ask questions on the freeradius-users mailing list.

https://freeradius.org/support/

**Comment by midobona** [comment]
but this is issue

**Comment by midobona** [comment]
#2077

**Comment by alandekok** [comment]
This is not a bug, because you have given us *zero* information about what you're doing, and *zero* information about what's going wrong.

If the only information you supply is "it doesn't work", then we can't help you.

If you want to know how to configure CoA in v3, ask questions on the freeradius-users mailing list.
