### ISSUE TITLE
freeradius works only in debug mode 

### ISSUE THREAD

**Issue by michelvio** [FreeRADIUS/freeradius-server#2197]
Hi,

We need support to check because our freeradius works in only debug mode (radiusd -X). When We do stop/start it stop to work.

[mavio@brhopnm01cpbrrj ~]$ rpm -qa | grep radius
freeradius-2.2.6-6.el6_7.x86_64

**Comment by alanbuxey** [comment]
Check the file permissions in and of  the log and config directories
(In this case running with radiusd -x (lower case) may help you see the
issue)

alan

On 15 Mar 2018 4:21 pm, "michelvio" <notifications@github.com> wrote:

Hi,

We need support to check because our freeradius works in only debug mode
(radiusd -X). When We do stop/start it stop to work.

[mavio@brhopnm01cpbrrj ~]$ rpm -qa | grep radius
freeradius-2.2.6-6.el6_7.x86_64

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/FreeRADIUS/freeradius-server/issues/2197>, or mute the
thread

**Comment by michelvio** [comment]
Thanks Alan. I'll try it and let you aware.

**Comment by michelvio** [comment]
Alan,

radiusd -x doesnt work.

We didn't change any permission in radius.

**Comment by arr2036** [comment]
http://freeradius.org/support/
