### ISSUE TITLE
is this even possible ?

### ISSUE THREAD

**Issue by minanagehsalalma** [FreeRADIUS/freeradius-server#2215]
https://www.youtube.com/watch?v=HoihKhQWZ7k&feature=youtu.be

if it's possible what are the steps to do this with your tool to make a pentesting  video just for Educational purpose ......

**Comment by alanbuxey** [comment]
hi,

yes, this sort of thing is possible (which is why any self-respecting
802.1X deployment would ensure that the CA details are being checked and
have their own special non public-CA cert.

you could search for ready made toolkits but you say "pentesting video just
for Educational purpose" - that video you posted is already clear enough -
you dont need
anymore than that - you simply need to state the reason why this is
possible and how to avoid/mitigate it - you dont need to create more
resources for script kiddies and
annoying jerks to use.

PS the demo shows EAP-TTLS/PAP being used - thus REALLY easy for getting a
password -  if the client is using PEAPv0/MSCHAPv2 you then need a little
more effort
to deal with the challenge-response..not much effort (doesnt take eg
cloudcracking anymore) but its not given to you on a plate.


alan

**Comment by minanagehsalalma** [comment]
@alanbuxey so how can i edit the algorithm to make it use EAP-TTLS/PAP ...  sorry i am not using the freeradius-server much ... i am kinda new to it😔😐😕😕😔😐😕😕

**Comment by alandekok** [comment]
Ask questions on the freeradius-users mailing list.

**Comment by arr2036** [comment]
@minanagehsalalma most people use filters to direct mailing list posts to specific folders so it doesn't interfere with directed email.  By continuing to post in the GitHub issue tracker (which is intended for communicating with developers and collaborating on the FreeRADIUS code base), you are creating unnecessary noise.  We will not provide support here and if you continue to request it you will be banned from this GitHub repository.  This is your only warning.
