### ISSUE TITLE
docker: alpine: add libpq

### ISSUE THREAD

**Issue by hanetzer** [FreeRADIUS/freeradius-server#2354]
# Issue type
- Feature Request - add libpq to stock docker alpine images
## How to reproduce the issue
Attempt to use rlm_sql_postgresql on the freeradius/freeradius-server:3.0.17-alpine
docker image.

Its 316kb according to https://pkgs.alpinelinux.org/package/edge/main/x86/libpq ,
plus or minus for other architectures probably, but overall a very small overhead
to make it more usable.

I hope this is the correct place to file this request, if not my apologies.

**Comment by mcnewton** [comment]
We built with all the modules, but left a lot of libraries out of the final image to keep it small. Otherwise it's hard to know where to draw the line on which libraries to include.

You should be able to do something like this in your own Dockerfile:
```
FROM freeradius/freeradius-server:latest
RUN apk add libpq
COPY raddb/ /etc/raddb/
```
then you get the libraries you need, without including them all in the base image.

Here's the comment in the source Dockerfile: https://github.com/FreeRADIUS/freeradius-server/blob/0e08a11b1ef60829da3f5e94279e8d3efe183bf5/scripts/docker/alpine/Dockerfile#L62-L68

**Comment by hanetzer** [comment]
Fair. I thought of that (and found said comment) shortly after posting this issue.
