### ISSUE TITLE
4.0.x rediswho module always returns fail status

### ISSUE THREAD

**Issue by gen2brain** [FreeRADIUS/freeradius-server#2369]
When rediswho module is used with redis cluster, final status is always `fail`, even when everything is `OK` and `success` (and verified in redis). You can see that from screenshot, very sorry I don't have text at the moment but I can send it later.

With some print/debug I see that code gets here https://github.com/FreeRADIUS/freeradius-server/blob/97ac84d82e422cb9bfd1c4e389d68a13a38e918a/src/modules/rlm_rediswho/rlm_rediswho.c#L160 , so some other case is missing? I am getting status `OK` from redis-cli for my query, but that doesn't get to `REDIS_REPLY_STRING`, perhaps that is `REDIS_REPLY_STATUS`? 

I can send more info, just not at this moment.

Thanks,
Milan

![screen13](https://user-images.githubusercontent.com/17418/49838802-adfc5e80-fdac-11e8-8b2f-b672d6546157.png)

**Comment by arr2036** [comment]
The idea is that LPUSH returns the index of the last item pushed onto the list of user sessions, and if that index is greater than ``trim_count`` it removes some historical sessions, so that ``trim_count`` sessions are maintained per user.

If you've altered the insert command to issue a command that's not ``LPUSH`` then the module isn't going to work as intended, and you should probably just use the redis expansion ``%{redis:<command>}``

**Comment by gen2brain** [comment]
Yes, LPUSH is modified to SET. Will need to read more about redis expansion, many thanks for answer.
