### ISSUE TITLE
Warnings about CVE2016-* shouldn't be coming up with OpenSSL 1.1.1a

### ISSUE THREAD

**Issue by tya99** [FreeRADIUS/freeradius-server#2487]
- Defect - Unexpected behavior (obvious or verified by project member).

# Defect
## How to reproduce the issue

Run FreeRadius 3.0.17 with a current release of [OpenSSL v1.1.1](https://www.openssl.org/blog/blog/2018/09/11/release111/)
 
```
Refusing to start with libssl version OpenSSL 1.1.1a  20 Nov 2018 0x1010101f (1.1.1a release) (in range 1.1.1a release - 1.1.1a rel)
Security advisory CVE-2016-6309 (OCSP status request extension)
For more information see https://www.openssl.org/news/secadv/20160926.txt
Once you have verified libssl has been correctly patched, set security.allow_vulnerable_openssl = 'CVE-2016-6309'
```

The problem is rather obvious: https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/src/main/tls.c#L75

**Comment by mcnewton** [comment]
Already fixed in v3.0.x

**Comment by alandekok** [comment]
The problem isn't rather obvious.  The problem is that the OpenSSL magic is confusing you.  And, you didn't bother looking at the commit history of that file.

**Comment by tya99** [comment]
Shouldn't the comment next to it be different if the version is different?

**Comment by alandekok** [comment]
You were told to go look at the commit history to see the source of the problem.  You were also told that the problem was fixed.  Instead, you're asking why the *fixed* code is getting the *old* behavior that's confusing you.

It's not.  The fixed code works.  The old code that has the error was fixed.  If you want to understand the difference, go read the commit history.
