### ISSUE TITLE
rlm_ldap and password private key certificate problem

### ISSUE THREAD

**Issue by Hadronx** [FreeRADIUS/freeradius-server#2932]
I tried to make an ldap + startssl connection with my active directory server.
If I use the radius certificate with the private key not encrypted, the radius server works correctly.

If I try to use ldap with the encrypted private key of the certificate, the freeradius server goes into error.
In the debug file I attach, there is a warning that says
**/etc/freeradius/3.0/mods-enabled/ldap[502]: The item 'private_key_password' is defined, but is unused by the configuration** 

my configuration file **mods-enabled/ldap** is

ldap{
    [....]
         tls {
                 start_tls = yes

                 ca_file = ${certdir}/CA_CHAIN_CRL.pem

                 ca_path = ${certdir}
                 certificate_file = ${certdir}/Server_Radius.crt
                 private_key_password = Password1234
                 private_key_file = ${certdir}/private/Server_Radius.key
                 random_file = /dev/urandom
                 dh_file = ${certdir}/dh

                 require_cert    = 'demand'

        }
    [...]
}
[debug.txt](https://github.com/FreeRADIUS/freeradius-server/files/3554526/debug.txt)

**Comment by alandekok** [comment]
That's because there is no `private_key_password` option in the configuration.  If there was one, it would have been documented.

The OpenLDAP API supports setting a private key file, but not a password.  See https://linux.die.net/man/3/ldap_set_option  and `LDAP_OPT_X_TLS_KEYFILE`.  There is no `LDAP_OPT_X_TLS_KEYPASSWORD` setting.

In this case, the FreeRADIUS warning successfully prevented you from creating a configuration that simply wouldn't work, and wouldn't do what you wanted.

**Comment by Hadronx** [comment]
OK, Thank you!
