### ISSUE TITLE
Build failure 3.0.19

### ISSUE THREAD

**Issue by bevclues** [FreeRADIUS/freeradius-server#3029]
Hello, thanks for your help over the weekend (3025), you were right - there was 2 SSLs installed on machine. I have re-build platform (Slackware 14.1) and installed MySQL 5.0.24 from source, for freeradius 3,0.19 attempted built form source with configure and make errors. I attache configure and make logs. 
[configure.log](https://github.com/FreeRADIUS/freeradius-server/files/3695913/configure.log)

[make.log](https://github.com/FreeRADIUS/freeradius-server/files/3695914/make.log)
[config.log](https://github.com/FreeRADIUS/freeradius-server/files/3695915/config.log)

I do not know enough about freeradius yet to interpret logs. Thanks for your help.

Bev Clues

**Comment by alandekok** [comment]
Questions belong on the freeradius-users mailing list.  As the github template makes clear, github issues are only for actual issues.

**Comment by bevclues** [comment]
Dear Alan, 

Thank you for your response all duly noted. I would like to put my point
of view whilst accepting that you can run your team and policy exactly
as you wish. For me I have to decide whether or not to join in. I am a
software developer with around 50 years of experience in small and large
projects. I am currently working on a secure email system which will
have a radius server as part of its back office services. For me, I
thought we had started a dialogue with my first problem, I acted on your
advice, reloaded linux, installed myql, tried to build freeradius and
there was a different kind of failure. In my view a failure of this kind
is usually a failure in the software, either configuration or build. As
such it was right to refer it back to the development team rather than
post to a users mailing list. I will not be doing this. I will fix the
problem myself or go to a different package. 

I will detach now. 

Best wishes with your excellent freeradius which I first found out about
in the O'Reilly book "RADIUS". 

Now on with my life. 

Bev

On 2019-10-07 12:25, Alan DeKok wrote:

> Questions belong on the freeradius-users mailing list. As the github template makes clear, github issues are only for actual issues. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/FreeRADIUS/freeradius-server/issues/3029?email_source=notifications&amp;email_token=AHVY34RFLLE3KIJGSYBGJELQNMMEPA5CNFSM4I6ATUL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAP6RDA#issuecomment-538962060
[2]

**Comment by jpereira** [comment]
Please take a look at scripts/docker and you will see some Linux distributions. well, the FreeRADIUS work/build pretty well among of them.

Think about to use another Linux distributions with a better package manager (Debian, Ubuntu, Centos) that will help you to don't waste time fixing basic dependency issues.

Btw, It's 2019! why use a awful thing like Slackware? I've stopped to use _that_ in the Slackware 7.1 and all my memories are about a poor internal package manager.

think about that.

**Comment by alandekok** [comment]
It's really quite simple.  Your original issue was because you installed OpenSSL 0.9.7.  A version which was first released in 2002.  If you read _any_ of the documentation about that release, it all says "do not use it or install it".  That issue was compounded by being unable to diagnose simple build issues.  I was able to diagnose the issue with minimal information.  Because that issue is extremely common, and trivial to debug and fix.

The next issue was to open another GitHub issue about more build errors.  Not only that, but the logs you posted above were *truncated*.  i.e. they showed absolutely nothing about any build errors.  This failure made the issue entirely useless.  It amounts to you opening the issue and saying 

_Stuff went wrong, but I'm not going to tell you what went wrong.  Please fix it._

I expect more from someone with "50 years of experience in small and large projects".

The final issue is complaining:

> In my view a failure of this kind is usually a failure in the software, either configuration or build. 

Maybe.  But since you failed to provide a build log which contained *errors*, it's impossible to tell.

> As such it was right to refer it back to the development team rather than post to a users mailing list. 

i.e. despite being told otherwise by the developers, you still think you're right.

Part of being a software developer is learning from experience.  I suggest trying it.  It's very handy!
