### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [FreeRADIUS/freeradius-server#3075]
Would you like to add more error handling for return values from functions like the following?
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [fb_set_tpb](https://github.com/FreeRADIUS/freeradius-server/blob/ed80bbf2b2bc349aeaab63da7378ca30a2718135/src/modules/rlm_sql/drivers/rlm_sql_firebird/sql_fbapi.c#L28)
- [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [trigger_exec_init](https://github.com/FreeRADIUS/freeradius-server/blob/204e3a1d0ce328180f48c39f3f60e9e129fc6bc7/src/lib/server/trigger.c#L136)

**Comment by alandekok** [comment]
To be honest, those are not issues.  On modern systems with over-commit, `malloc()` doesn't fail.  Even if it does fail, there is nothing an application can do when it runs out of memory.  The only *safe* thing to do is exit.

Similar arguments go for `pthread_mutex_init()`.  If that fails, then either the pthread implementation is broken, OR the system memory is corrupt.  And there's nothing an application can do about either one.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by alandekok** [comment]
I explained *why* these checks are useless in the real world.  You don't have a counter-argument.  Instead of discussing it logically using facts and evidence, you resort to appeals to authority.

Checking return values *is* important where you can do something to recover from the error.  Unless you have magical knowledge that no one else in the world possesses, it's essentially impossible for a Unix application to recover from an OOM situation.

I suggest that useless checks are irrelevant, and we will not be adding them to the software.  

If you don't like the way we write our software, you're free to fork it.  Then you can fix any issues you think are necessary.
