### ISSUE TITLE
server.pem contains the wrong key

### ISSUE THREAD

**Issue by enoch85** [FreeRADIUS/freeradius-server#3706]
# Defect
## How to reproduce the issue

1. Install FreeRADIUS on Ubuntu 20.04 using their packaging.
2. Try to create new certs according to ../certs/README
3. Issue the commands described in the README for CA and SERVER

 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring

First of all, server.pem are created with the wrong permissions, so you need to manually `chmod 644`. When that's done, this happens:

```
tls: Failed reading private key file "/etc/freeradius/3.0/certs/server.pem": error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch
rlm_eap_tls: Failed initializing SSL context
rlm_eap (EAP): Failed to initialise rlm_eap_tls
/etc/freeradius/3.0/mods-enabled/eap[14]: Instantiation failed for module "eap"
```

I've been over this several times, and it's always the same. I also tried to run only `make`, but that failed as well, saying that an certificate already exists, even if I did `make destroycerts` **just** before.

Thanks for looking into this!

## Full backtrace from LLDB or GDB

```text
???
```

**Comment by alandekok** [comment]
> server.pem are created with the wrong permissions, so you need to manually chmod 644

The `server.pem` file is created using the default "umask" taken from your shell.  The only `chmod` done by the scripts are to set `g+r` on it

If you run the scripts and OpenSSL can't start, then they created the wrong / incorrect certificates.

To be honest, it looks like Ubuntu has broken the server.  These errors do *not* occur in the default configuration.  We run these checks (and more) in Travis all of the time, and it passes:  https://travis-ci.org/github/FreeRADIUS/freeradius-server

Please try this using the files taken from _our_ release.  If they still fail, we'll look into it.  Otherwise it looks like an Ubuntu issue.

**Comment by jpereira** [comment]
Official packages could be found at https://networkradius.com/packages/

**Comment by enoch85** [comment]
Thanks guys! <3

Will probably reinstall the server tomorrow for the 10:th time :D This time with the official packages.

**Comment by enoch85** [comment]
@jpereira @alandekok Noticed now that Focal isn't supported. 

Do you know when support will be added, or does the Bionic repo work for Focal as well?

Thanks again!

**Comment by enoch85** [comment]
Installed from source, everything is working. 🥇
