### ISSUE TITLE
DHCP Domain-Search (option 119) not properly presented (not working)

### ISSUE THREAD

**Issue by tuxjz** [FreeRADIUS/freeradius-server#4367]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

I've tried to use DHCP-Domain-Search (119) in addition to DHCP-Domain-Name (15), both configured as plain (different) strings in `mods-config/files/dhcp` in network section.
With default `dictionary.dhcp` format in octets it shows as hex in debugging mode (but client didn't get it and it is incomplete/malformed packet), when I change it to string, it shows plain string, but DHCP offer is still malformed packet - doesn't have the End (255) option.

Any help would be appreciated, because I didn't find anything about this in the docs, so I'm not sure, if I'm configuring something wrong or it is just not working as expected.

Tested on Freeradius 3.0.23 and 3.0.25 (CentOS 7 rpms from networkradius repo).

### Log output from the FreeRADIUS daemon

```shell
dictionary.dhcp with octets:
...
(1)   DHCP-Message-Type = DHCP-Request
(1)   DHCP-Parameter-Request-List = DHCP-Subnet-Mask
(1)   DHCP-Parameter-Request-List = DHCP-Classless-Static-Route
(1)   DHCP-Parameter-Request-List = DHCP-Router-Address
(1)   DHCP-Parameter-Request-List = DHCP-Domain-Name-Server
(1)   DHCP-Parameter-Request-List = DHCP-Domain-Name
(1)   DHCP-Parameter-Request-List = DHCP-Domain-Search
(1)   DHCP-Parameter-Request-List = 252
...
(1)   DHCP-Domain-Search = 0x73776974636865732e6e6174
...
	DHCP-Domain-Search = 0x73776974636865732e6e6174
Sending DHCP-Ack Id 320bd358 from 172.16.205.31:67 to 172.16.204.1:67
(1) Finished request
(1) Cleaning up request packet ID 839635800 with timestamp +7


And same with dictionary.dhcp with string:
...
	DHCP-Domain-Search = "switches.nat"
Sending DHCP-Ack Id 320bd356 from 172.16.205.31:67 to 172.16.204.1:67
(0) Finished request
(0) Cleaning up request packet ID 839635798 with timestamp +4

No obvious errors.
```

**Comment by alandekok** [comment]
The format of Option 119 is define in [RFC 3397](https://datatracker.ietf.org/doc/html/rfc3397).   The encoding format is not simple domain names `www.example.com`, but is instead compressed using the DNS compression.  Unfortunately, v3 does not support automatically compressing domain names.

The dictionaries have this attribute as type `octets`, because of the DNS compression.  This means that if you want to use the attribute, you'll have to manually convert the domain names to the compressed format, and then enter them as hex strings in the configuration.

As for option 255, you should look at the PCAP packet traces, not the debug output.  The encoder _always_ adds option 255 at the end of the packet.

The reason the client is saying "malformed DHCP packet" is that option 119 is not encoded correctly.

The solution is to encode it yourself, by hand.

We'll see if we can update this in a future release.

**Comment by tuxjz** [comment]
Thanks for explaining.

After closer look in pcap, ending option 255 (ff in raw view) is present, only wireshark doesn't show it due to malformed packet...

I've successfully workarounded crafting it by hand by copying hex stream from previous ISC DHCP offers, stripping first two bytes (in my case 0x7721) containing option number and length (as FR3 is doing it already 👍). Now it is working properly.

Thank you very much for your help!
If it is not necessary for tracking this issue onwards, we can close this issue.
