### ISSUE TITLE
[defect]: FreeRadius crashes on opening more than 254 ports to listen on 

### ISSUE THREAD

**Issue by harshita93** [FreeRADIUS/freeradius-server#4857]
### What type of defect/bug is this?

Crash or memory corruption (segv, abort, etc...)

### How can the issue be reproduced?

Add listen section in default file : 
listen {
    type = "auth"
    ipaddr = *
    port = 4400
}
Opening ports from 4001 to 4400

### Log output from the FreeRADIUS daemon

```shell
Listening on auth address * port 1812 bound to server default
Listening on acct address * port 1813 bound to server default
Listening on auth address :: port 1812 bound to server default
Listening on acct address :: port 1813 bound to server default
Listening on auth address * port 4001 bound to server default
Listening on auth address * port 4002 bound to server default
Listening on auth address * port 4003 bound to server default
Listening on auth address * port 4004 bound to server default
Listening on auth address * port 4005 bound to server default
Listening on auth address * port 4006 bound to server default
Listening on auth address * port 4007 bound to server default
...
..
...
...
Listening on auth address * port 4248 bound to server default
Listening on auth address * port 4249 bound to server default
Listening on auth address * port 4250 bound to server default
Listening on auth address * port 4251 bound to server default
Listening on auth address * port 4252 bound to server default
Failed adding event handler for socket: Too many readers
```

**Comment by harshita93** [comment]
Long list of Listen section was added to default config to listen on ports from 4001 to 4400, only ports till 4252 gets open and freeradius crashes

**Comment by alandekok** [comment]
If you read the log messages, you'll see that it exits with an error.  It definitely doesn't crash.

The larger question here is why are you opening 400 sockets?

v3 is limited to 512 sockets at a time.  So if you're seeing limits at ~256 sockets, you're running an older version of the server.

If you want to use more than 512 sockets at a time, you can edit `src/lib/packet.c`, see `MAX_SOCKETS`.  And edit `src/lib/event.c`, see `FR_EV_MAX_FDS`

But changing these is probably not a good idea.  There is just no good reason to open 400 sockets.  The server operates fine with a smaller number of sockets.  And the `virtual_server` configuration in the `client` configuration lets you have multiple different clients, each with different policies, all using one socket.

So please explain what you're trying to do.  The problem is not "I can't open 400 sockets".  The problem is why you think it's useful to open 400 sockets  What problem are you trying to solve which requires 400 sockets?

And why is the existing functionality of the server not good enough to solve that problem?

**Comment by harshita93** [comment]
Hello Alex, 
Thank you for your response 

I am integrating freeradius with a VPN solution. My use case is that I need to isolate user authentication based on VPN connections. NAS uses radius port number to isolate connections coming on which VPN connections which i have mapped to a unique radius port. That's why I need to spin up around 400 or more radius ports which will correspond to 400 VPN connections. 
On radius i have policy which checks destination port of access request and then allow or reject. I have created a user table in sql which will  be dynamically populated to provide correlated users to radius ports which in turn is used by the policy filter. 
The client which is actually NAS sending the auth request is just one IP but access request destination ports will be various radius ports.
I am using freeradius version 3.0.13.@CentOS ~]# radiusd -v
radiusd: FreeRADIUS Version 3.0.13, for host x86_64-redhat-linux-gnu, built on Sep 30 2020 at 16:16:12
FreeRADIUS Version 3.0.13
Copyright (C) 1999-2017 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGHT

I am basically trying to utilize attributes in the access request that can tell radius server to differentiate the users auth request relation with the VPN connection request it is using and thought only may be radius port might be the best bet here.

Hope this helps to understand what I am trying to do with freeradius.  I have not used Virtual servers in this case yet. I am still using all default configs 

Please let me know if I can provide additional information to clarify. 
Looking forward to your suggestions.

**Comment by alandekok** [comment]
If you're using 3.0.13, you should really upgrade.  There are many bug fixes and features added in newer versions of the server.

As for the underlying issue, you can isolate user authentication by user names.  i.e. `user@gmail.com` is different than `user@example.org`.  This is how people have traditionally done user isolation.

If you can't change the user names, then there is likely another attribute in the RADIUS packet you can use to tell the users apart.  You can key off of that to do user isolation.  Read the debug log to see what is in the packets.

In the end, there's no reason for us to fix it.  You can edit the source if you really need to increase the number of sockets.  But everyone else doesn't need this change, even if they have similar VPN setups.  Because there are other, and better ways to address this.

Since you have work-arounds, this isn't a bug, and we're not going to do any code changes.

**Comment by jpereira** [comment]
@harshita93The version 3.0.13 is from Mar 6, 2017. As @alandekok said, please upgrade to the latest available at https://networkradius.com/packages/

**Comment by harshita93** [comment]
I very much appreciate you inputs, I will upgrade and test with the latest
version of freeradius. I did read that in v4 there is not going to be
limits on sockets.

I have installed freeradius on debian, what should be the exact location
where can i find src/lib/packet.c , is this a systems OS file or specific
file that freeradius has ?

**Comment by alandekok** [comment]
You will have to build the server from source.  You can't find the source by installing the binary packages.
