### ISSUE TITLE
[defect]: double free in src/listen/ldap_sync/proto_ldap_sync_ldap.c

### ISSUE THREAD

**Issue by icy17** [FreeRADIUS/freeradius-server#4863]
### What type of defect/bug is this?

incorrect 3rd party API usage

### How can the issue be reproduced?

Double free in [proto_ldap_sync_ldap.c](https://github.com/FreeRADIUS/freeradius-server/blob/master/src/listen/ldap_sync/proto_ldap_sync_ldap.c) line 423 (498 goto error), 663  (line 744 goto sync_error). This `msg` may have already been cleared in the line 496 , 742. 
![image](https://user-images.githubusercontent.com/39425646/214767847-c1f56d53-70cf-4139-9e21-1fd77764be04.png)
![image](https://user-images.githubusercontent.com/39425646/214767878-fe716bb4-d307-4dec-80a5-f2850ee2cbe3.png)
![image](https://user-images.githubusercontent.com/39425646/214767904-b954249d-175e-4063-9a45-d47299384132.png)

### Log output from the FreeRADIUS daemon

```shell
None
```

**Comment by ndptech** [comment]
Line 744 will never have `ret < 0` if the path through line 742 has occurred - `ret` can only be < 0 if a callback returns a negative, and line 742 is only run if there is no callback.  So that path will not double free.

If the path involving line 498 fails, then something has gone seriously wrong and the server is probably crashing anyway - failing to insert an entry into a dlist means the list is fundamentally broken or not initialised.  I will however resequence the dlist insert and `ldap_msgfree()` just for correctness.
