### ISSUE TITLE
[defect]: Python3 module still crashes freeradius

### ISSUE THREAD

**Issue by Sprinterfreak** [FreeRADIUS/freeradius-server#4952]
### What type of defect/bug is this?

Crash or memory corruption (segv, abort, etc...)

### How can the issue be reproduced?

see #4951 , debian bullseye (stable)

### Log output from the FreeRADIUS daemon

```shell
see #4951
```

### Relevant log output from client utilities

Does not apply, server unable to start

**Comment by Sprinterfreak** [comment]
Sadly issue got closed unresolved.

  * Custom compiling for security related software on production systems is of course not an option as it breaks maintainability and does not get updates from upstream security team - not an option
  * The mentioned repos do not provide freeradius-python3 for debian at all - not an option
  * python2 is still shipped with freeradius. Python2 is officially dead as of january 1st 2020. (No security updates!) - dangerous

The answers in the original issue #4951 did not remotely address the issue.

So what is the current state of python3? Officially unsupported?

**Comment by arr2036** [comment]
Checking through the Network RADIUS debian packaging rlm_python3 should be installed with the main FreeeRADIUS package. Have you confirmed that rlm_python3 is not installed? or were you inferring that because a discreet package is not provided?

In later major releases of FreeRADIUS (v4) support for Python 2 is removed, and rlm_python provides Python 3 support only.

The backtraces you provided showed only the deepest stack frame so we can't determine anything more regarding your issue.

**Comment by alandekok** [comment]
> Custom compiling for security related software on production systems is of course not an option as it breaks maintainability and does not get updates from upstream security team - not an option

i.e. You're not willing to build your own packages, but you want us to do that work.

> The mentioned repos do not provide freeradius-python3 for debian at all - not an option

The simple answer is to build your own packages.  It's not hard.   Your reasons for not building the packages are irrelevant.

> python2 is still shipped with freeradius. Python2 is officially dead as of january 1st 2020. (No security updates!) - dangerous

I gave reasons why python2 was still packaged.  And places where it wasn't packaged.  Did you not read that response?  Perhaps you didn't understand it?

If people want to use python2 due to compatibility issues, they're free to make an informed decision.  I think everyone using Python2 is aware that it is EOL, and has no security fixes.  It can still be safe to use in a controlled environment.

Or maybe you believe that it's insecure to ship a Python2 module, even if no one uses it.  That makes no sense, but whatever.

Even with all of that, I find it telling that I gave reasons why Python2 was still OK, and you've just ignored those reasons.

But if you have reasons why you can't build your own packages, well... we're supposed to accept that, too.  And work hard to fix the packages to keep you happy.  Is it really that difficult for you to type `make deb`, and build your own packages?

If your goal is to ask us to help you, you are your own worst enemy.  You come across as dismissive, ignorant, condescending, and arrogant.  You expect us to do what you want and to listen to you, but you're not willing to listen to us.

Whether we fix this issue (or not), it will be because of our continued efforts to make FreeRADIUS great, and to give back to the community. 

I'm closing this issue (again) because of your hostile and arrogant attitude.  If you keep opening issues which contains condescending and ignorant statements, we will simply ban you from the FreeRADIUS repo.
