### ISSUE TITLE
[defect]: mod_checksimul converts NAS port explicitly to integer

### ISSUE THREAD

**Issue by tarelda** [FreeRADIUS/freeradius-server#5010]
### What type of defect/bug is this?

Unexpected behaviour (obvious or verified by project member)

### How can the issue be reproduced?

My NASes send NAS-Port-Id as a string. Freeradius explicitly converts them to integer before handing them to checkrad script.

https://github.com/FreeRADIUS/freeradius-server/blob/979424b0a959c457fc68102243920f651695eb30/src/modules/rlm_sql/rlm_sql.c#L1738

Despite the fact that NAS-Port-Id is accepted as a string by the other modules. This seems very inconsistent and in the end it is converted to string while flattening into checkrad arguments. 

### Log output from the FreeRADIUS daemon

```shell
not relevant here
```

**Comment by alandekok** [comment]
I think this should work, but it will result in a behavior change for 3.2.  the session zap will now produce a correct `NAS-Port-Id` instead of an incorrect `NAS-Port`.  This change is only for the SQL module.

I think this change won't go into 3.0, as it's a behavior change.  So we can just document the behavior there, and move on
