### ISSUE TITLE
Request: mods-available/dhcpv6

### ISSUE THREAD

**Issue by hollyclergyman** [FreeRADIUS/freeradius-server#5044]
### Message

Dear all,
Thanks at the first place for the great work, freeradius provides to the network. I noticed, that freeradius supports DHCPv6 in addition to DHCPv4. Yet, there is no file available for configuration of the DHCPv6 site (is it called like that? I'm not sure), which may be necessary, once dhcpv6 has been enabled by linking it in the sites-enabled directory of raddb. 
Would it be possible to add a file in mods-available for DHCPv6, containing a sample configuration with the required parameters?
If you hint me at the correct place to look at, I may also fork the repository, write such a file and provide you a pull request. 
Kind regards
Thomas Rahimi

**Comment by alandekok** [comment]
There is `sites-available/dhcpv6` in the `master` branch.  That implements a server which listens on DHCPv6.

If there was `mods-available/dhcpv6`, that would be for originating DHCPv6 packets as a client.  We are not doing that right now.

So the server already has the documentation you want.

Note that v3 doesn't have `sites-available/dhcpv6`, because v3 doesn't implemnt DHCPv6.
