### ISSUE TITLE
Question about fixing memory leak

### ISSUE THREAD

**Issue by klssstis** [FreeRADIUS/freeradius-server#5182]
### Message

Hello, is this https://github.com/FreeRADIUS/freeradius-server/commit/33b0b7d31bae7b9e78a23496b2c2f36693fb2761 a one-time leak or could it lead to an accessibility issue?

**Comment by alandekok** [comment]
Open Source projects have recently had many nonsensical CVE reports from people scanning the commit logs.  If they see messages like "leak" or other issue, they file a CVE.  Presumably in order to either get some minor fame, or to get some kind of bounty.

We do not participate in such issues.

In this case, the code is pretty obvious.  On top of that, it's sheer laziness to ask a question instead of reading the code.

And even without that, the issue template you deleted has explicit instructions for what is a good issue, and what information we need from an issue.

This comment is not helpful, and is not useful.  We are not going to go down the path of explaining the code to people who can't be bothered to read the code and think about it.
