### ISSUE TITLE
[defect]: systemd[1]: freeradius.service: Main process exited, code=killed, status=11/SEGV

### ISSUE THREAD

**Issue by Popyllol** [FreeRADIUS/freeradius-server#5235]
### What type of defect/bug is this?

Crash or memory corruption (segv, abort, etc...)

### How can the issue be reproduced?

Put a certificate with DOS linefeeds on a connected radsecproxy.
I allready openened an RFE at the radsecproxy project
  https://github.com/radsecproxy/radsecproxy/issues/139
BUT freeradius should behave better if it gets a certificate with DOS linefeeds or even rubbish from a remote site. SEGV should not be an option.

```
# freeradius -v
radiusd: FreeRADIUS Version 3.0.26, for host x86_64-pc-linux-gnu, built on Jan  4 2023 at 03:23:09
FreeRADIUS Version 3.0.26
Copyright (C) 1999-2021 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGHT
```

This is an Ubuntu 22.04 instance:
```
# dpkg -l freeradius
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version                                         Architecture Description
+++-==============-===============================================-============-======================================================
ii  freeradius     3.0.26~dfsg~git20220223.1.00ed0241fa-0ubuntu3.1 amd64        high-performance and highly configurable RADIUS server
```

### Log output from the FreeRADIUS daemon

```shell
/var/log/kern/log:
kernel: freeradius[5313]: segfault at 78 ip 00007fc403a593c2 sp 00007fc3fcb73810 error 4 in libfreeradius-radius.so[7fc403a51000+22000]
kernel: freeradius[5324]: segfault at 78 ip 00007f92c0bda3c2 sp 00007f92b94f3810 error 4 in libfreeradius-radius.so[7f92c0bd2000+22000]
kernel: freeradius[5334]: segfault at 78 ip 00007f9c507063c2 sp 00007f9c4901f810 error 4 in libfreeradius-radius.so[7f9c506fe000+22000]
kernel: freeradius[5343]: segfault at 78 ip 00007ff1812423c2 sp 00007ff179b5b810 error 4 in libfreeradius-radius.so[7ff18123a000+22000]
kernel: freeradius[5351]: segfault at 78 ip 00007ff8a32253c2 sp 00007ff89c33f810 error 4 in libfreeradius-radius.so[7ff8a321d000+22000]
kernel: freeradius[5359]: segfault at 78 ip 00007f49c3fa83c2 sp 00007f49bd8c3810 error 4 in libfreeradius-radius.so[7f49c3fa0000+22000]
kernel: freeradius[5374]: segfault at 78 ip 00007f39d942a3c2 sp 00007f39d1542810 error 4 in libfreeradius-radius.so[7f39d9422000+22000]
kernel: freeradius[5392]: segfault at 78 ip 00007f877a66e3c2 sp 00007f8773f89810 error 4 in libfreeradius-radius.so[7f877a666000+22000]
kernel: freeradius[5402]: segfault at 78 ip 00007f22f456a3c2 sp 00007f22ed684810 error 4 in libfreeradius-radius.so[7f22f4562000+22000]
kernel: freeradius[5411]: segfault at 78 ip 00007f2357d383c2 sp 00007f2350e52810 error 4 in libfreeradius-radius.so[7f2357d30000+22000]
kernel: freeradius[5420]: segfault at 78 ip 00007f61f2e533c2 sp 00007f61ebf6d810 error 4 in libfreeradius-radius.so[7f61f2e4b000+22000]
kernel: freeradius[5427]: segfault at 78 ip 00007fab4f2833c2 sp 00007fab4939f810 error 4 in libfreeradius-radius.so[7fab4f27b000+22000]
```

**Comment by alandekok** [comment]
Unfortunately log messages with random hex values don't help a lot.  Please

* install debug symbols
* run the server in debug mode under gdb
* get a stack trace with actual symbols and line numbers

The harder it is for us to reproduce a bug, the less likely we're doing to spend time to look into it.

And I'll add that when certificates are sent on the wire, they use ASN.1:  https://datatracker.ietf.org/doc/html/rfc4346#section-7.4.2

i.e. any DOS line feeds are stripped, and the certificate is encoded using a binary form.

So something else is going on.

In addition, any certificate handling is done by OpenSSL.  So perhaps the SEGV is in an OpenSSL library somewhere.  But we can't tell, because the log output contains no useful information.  The only two bits of information are "FreeRADIUS" and "SEGV".  Everything else is meaningless.

Please give some more information here.  What's in the certificate?

Can you create test certificates and add them to this bug report?  Can you make it *easy* for us to track down and test this problem?

Right now, the report is little more than "I did a bunch of stuff and bad things happened".   Giving as little information as possible in order to reproduce an issue is *not* a recommended approach.  Instead, give as much information as possible.

**Comment by Popyllol** [comment]
No possibilities to take further logs. -> Close
