### ISSUE TITLE
The LDAP module "tls" section should be simplified

### ISSUE THREAD

**Issue by alandekok** [FreeRADIUS/freeradius-server#583]
start_tls is unnecessary.  instead like everything else, it should do TLS if the tls{...} section is defined.

require_cert should be removed from the mods-config/ldap file.  There are few reasons to allow people to connect to random LDAP servers.

AND / OR to the above, we probably should take a look at adding something like require_cert to the normal tls client configuration.

**Comment by arr2036** [comment]
Whilst theoretically enabling/disabling a feature by commenting/uncommenting the section would be a 'clean' design, that's just not how its done in other areas of the server.  Commenting out a section in most other places means use the defaults for that section, not disable the functionality.

Sections are (in most areas of the server) just structural parts of the configuration, they don't infer anything other than a grouping of configuration items.  Where a feature does need to be enabled/disabled there's an explicit toggle ``enable = <bool>`` config item (see OCSP, and session resumption).

From a usability point of view, having a little toggle switch that can be moved to the 'off' position is vastly more intuitive than having to rip the whole control panel off the wall.

So if there's still a desire to ensure absolute consistency with the rest of the server, then an 'enable' toggle could replace 'start_tls'.  It'd still be inconsistent with the vast majority of LDAP client implementations, but for those who'd never used LDAP before it'd probably be more intuitive.

**Comment by alandekok** [comment]
It's also the the TLS configuration for LDAP is different from the other TLS sections.  We should have consistent config, even if the underlying implementations are different.

**Comment by arr2036** [comment]
So re-reading this again, I still don't think there's anything that needs to be done.  You can't enable/disable ldaps by commenting or uncommenting the tls section because libldap doesn't allow that, we'd have to start mucking with URLs, removing the scheme's the user had specified and replacing them.

It's like in rlm_rest, forcefully changing ``http://example.org`` to ``https://example.org`` if people include a TLS section in the configuration, seems like a bad idea to me.

Even with that you *STILL* need ``start_tls`` to specify *WHICH* type of TLS negotiation you want to use.  ``start_tls`` isn't a verb in this case, it's the name of an extension which is used to negotiate TLS on the connection.

Even my comments at the top of this thread about setting require_cert are probably wrong, because libssl can get defaults outside of the LDAP module's config.  It may still have a ca_path set even if we don't specify one.

I guess we could move the LDAP specific TLS options into their own subsection if we really wanted absolute consistency.

**Comment by arr2036** [comment]
Also, in the case where you start by connecting locally to an LDAP replica, and then following redirects out that use ldaps://, you don't want to start with TLS right away, but still want to specify options if it's used.
