### ISSUE TITLE
DHCP - FreeRADIUS complains about conflicting packets

### ISSUE THREAD

**Issue by nchaigne** [FreeRADIUS/freeradius-server#941]
I have a FreeRADIUS doing DHCP (configured with "cleanup_delay = 0").

I'm sending lots of DORA transactions to the server.
I never reuse the same transaction ID, except within a given DORA (as specified in RFC 2131, the ID of the Request should be the same as in the corresponding Offer / Discover).

The issue is the following:

I regularly get the following message in the logs:

	Fri Mar 27 17:22:36 2015 : Error: Received conflicting packet from client dhcp port 42067 - ID: 98534 due to unfinished request.  Giving up on old request. child_state: 2, codes=1025 1027

(I added "child_state: 2, codes=1025 1027" to try and understand what's going on...)

From what I understand, this happens when:
FreeRADIUS has processed a given Discover, sent back an Offer;
Receives the Request corresponding to this Offer (same transaction Id), and finds the Discover still in his request hash (and apparently still with a child_state == REQUEST_RUNNING).

I'm not sure how it can happen.

Isn't the first packet supposed to be cleaned-up immediately with "cleanup_delay" set to 0 ?
And even if it isn't, how can the child still be running the request ?

Maybe there's a race condition ? it only seems to happen under heavy load.

**Comment by alandekok** [comment]
Is this with v3.0.x head?  Or another version?

  You can work around this by updating the DHCP �listen� section to have:

performance {
	skip_duplicate_checks = true
}

  So it will skip all of the conflicting packet issues.

**Comment by nchaigne** [comment]
That was with the 3.0.x HEAD yes.
The configuration "skip_duplicate_checks = yes" works, I no longer have these errors.

Thanks !


I think this would be a good idea to add this (maybe commented) in "raddb\sites-available\dhcp".

**Comment by alandekok** [comment]
On Mar 27, 2015, at 12:22 PM, Nicolas C <notifications@github.com> wrote:
> That was with the 3.0.x HEAD yes.
> The configuration "skip_duplicate_checks = yes" works, I no longer have these errors.
> 
> Thanks !
> 
> I think this would be a good idea to add this (maybe commented) in "raddb\sites-available\dhcp".

  No� it should just be on by default.  There�s really no reason to do duplicate checks for DHCP

**Comment by nchaigne** [comment]
Is this documented somewhere ? I could not find anything about this parameter.

**Comment by alandekok** [comment]
It�s not documented.  There are few things like this which will confuse people and let them break their systems.  They�re useful if you know what you�re doing, but not useful for other people.

  I�ve pushed a fix which disables duplicate checking for DHCP sockets.  That should be used instead of the �performance� section.

**Comment by nchaigne** [comment]
OK, thanks again :)

**Comment by reza-ebrahimi** [comment]
@alandekok @arr2036 Our FreeRADIUS version is 3.0.17 and we get following error:
```
Ignoring duplicate packet from client ... port ... - ID ... due to unfinished request in component accounting module
```

Is `skip_duplicate_checks = true` valid and working for radius.conf configuration?

**Comment by kholud2017** [comment]
hi 
we show the following logs on radius.log , kindly advice how we can solve it 
Mon Jul 25 10:30:08 2022 : WARNING: (32435211) WARNING: Module rlm_radutmp became unblocked
Mon Jul 25 10:30:08 2022 : WARNING: (32435229) WARNING: Module rlm_radutmp became unblocked
Mon Jul 25 10:30:08 2022 : WARNING: (32435231) WARNING: Module rlm_radutmp became unblocked
Mon Jul 25 10:30:08 2022 : WARNING: (32435230) WARNING: Module rlm_radutmp became unblocked
Mon Jul 25 10:30:08 2022 : WARNING: (32435236) WARNING: Module rlm_radutmp became unblocked
Mon Jul 25 10:30:08 2022 : WARNING: (32435239) WARNING: Module rlm_radutmp became unblocked
Mon Jul 25 10:30:08 2022 : WARNING: (32435240) WARNING: Module rlm_radutmp became unblocked
Mon Jul 25 10:30:08 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 83 due to unfinished request in module <queue>.  Giving up on old request.
Mon Jul 25 10:30:08 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 87 due to unfinished request in module <queue>.  Giving up on old request.
Mon Jul 25 10:30:08 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 91 due to unfinished request in module <queue>.  Giving up on old request.
Mon Jul 25 10:30:08 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 95 due to unfinished request in module <queue>.  Giving up on old request.
Mon Jul 25 10:30:08 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 99 due to unfinished request in module <queue>.  Giving up on old request.
Mon Jul 25 10:30:08 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 107 due to unfinished request in module detail.  Giving up on old request.
Mon Jul 25 10:30:09 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 111 due to unfinished request in module detail.  Giving up on old request.
Mon Jul 25 10:30:09 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 115 due to unfinished request in module detail.  Giving up on old request.
Mon Jul 25 10:30:09 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 119 due to unfinished request in module detail.  Giving up on old request.
Mon Jul 25 10:30:09 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 123 due to unfinished request in module detail.  Giving up on old request.
Mon Jul 25 10:30:09 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 127 due to unfinished request in module detail.  Giving up on old request.
Mon Jul 25 10:30:09 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 131 due to unfinished request in module detail.  Giving up on old request.
Mon Jul 25 10:30:09 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 135 due to unfinished request in module detail.  Giving up on old request.
Mon Jul 25 10:30:09 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 139 due to unfinished request in module detail.  Giving up on old request.
Mon Jul 25 10:30:09 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 143 due to unfinished request in module detail.  Giving up on old request.
Mon Jul 25 10:30:09 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 147 due to unfinished request in module detail.  Giving up on old request.
Mon Jul 25 10:30:09 2022 : Error: Received conflicting packet from client x.x.x.x port 1646 - ID: 151 due to unfinished request in module detail.  Giving up on old request.
Mon Jul 25 10:30:09 2022 : WARNING: (32435292) WARNING: Module rlm_detail became unblocked
Mon Jul 25 10:30:09 2022 : WARNING: (32435287) WARNING: Module rlm_detail became unblocked
Mon Jul 25 10:30:09 2022 : WARNING: (32435303) WARNING: Module rlm_detail became unblocked
Mon Jul 25 10:30:09 2022 : WARNING: (32435295) WARNING: Module rlm_detail became unblocked
Mon Jul 25 10:30:09 2022 : WARNING: (32435319) WARNING: Module rlm_detail became unblocked
Mon Jul 25 10:30:09 2022 : WARNING: (32435307) WARNING: Module rlm_detail became unblocked
Mon Jul 25 10:30:09 2022 : WARNING: (32435309) WARNING: Module rlm_detail became unblocked
Mon Jul 25 10:30:09 2022 : WARNING: (32435325) WARNING: Module rlm_detail became unblocked
Mon Jul 25 10:30:09 2022 : WARNING: (32435327) WARNING: Module rlm_detail became unblocked
Mon Jul 25 10:30:09 2022 : WARNING: (32435329) WARNING: Module rlm_detail became unblocked
Mon Jul 25 10:30:09 2022 : WARNING: (32435328) WARNING: Module rlm_detail became unblocked

and after sometimes (days ) the service becomes down or stuck with talloc error 
 talloc abort: logic error in talloc_memlimit_shrink” 

can anyone help me to solve this issue ?
I have radius version  FreeRADIUS Version 3.0.23 with oracle 12C

thanks
