### ISSUE TITLE
radclient -f option not support single file witth blank line separated multiple tickets

### ISSUE THREAD

**Issue by Shamey** [FreeRADIUS/freeradius-server#989]
Using Freeradius3.0.4 on Centos7.  Running radclient command below with a ticket file with two accounting-request packets which are blank line separated.  Seems radclient does not allow any blank lines and reports error below.  radclient should allow blank line separated packets in file as per man page. It does so for type auth but not type acct. This would essential to support large ticket file re-processes for testing (after top/tail clean-up) 

[root@localhost radius-tests]# radclient -F -s -x -d /etc/raddb 127.0.0.1 acct testing123 -f ticket_test2
(0) Error parsing "ticket_test2": Invalid attribute name
radclient: Failed parsing input files
[root@localhost radius-tests]#

**Comment by arr2036** [comment]
IIRC this was fixed in a later version. Please try v3.0.x HEAD before opening issues in future.

**Comment by Shamey** [comment]
Im running later freeradius3.0.10 and see same bug. radclent not allow newliine delimited tickets in file with acct . Any chance of knowing what version this was fixed in as i have no original bug reference details to identify same..

My version : radclient version 3.0.10, built on Feb  3 2016 at 14:23:32

[root@xxx]# /usr/local/freeradius/bin/radclient -F -s -x -d /usr/local/freeradius/etc/raddb -f ticket_test2 localhost acct testing123
(0) Error parsing "ticket_test2": Invalid attribute name
radclient: Failed parsing input files
[root@xxx]#

**Comment by Shamey** [comment]
ah works if i use auto and set Packet-Type for each ticket in file.

**Comment by elie2282** [comment]
-bash-4.2#
-bash-4.2# sh /home/vpn/ibmverify/IBM-Verify-FreeRADIUS-master/test_verify_radius.sh  simple 192.168.xx.xx 1812 cisco123 user123 p@ssword
Initiating the policy with OTP supplied\r\n
User-Name = user123
NAS-IP-Address = 127.0.0.1
User-Password = p@ssword
(0) Error parsing "/tmp/tmp.QjEH1L3csX"
radclient: Failed parsing input files

-bash-4.2#


dears i got this error.
however when i changed the password of user123
it worked.
when I set the old password, I got the same error.
I think this error appears only when using this test function. 
In case I try from the cisco VPN app using the old password it is working normally.

**Comment by elie2282** [comment]
Dears,
any idea how to solve the below error please:

-bash-4.2#
-bash-4.2# docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                                 NAMES
76210001e236        jared/verify-freeradius   "/bin/sh -c 'radiusd…"   2 years ago         Up 26 hours         1813/tcp, 0.0.0.0:1812->1812/tcp, 0.0.0.0:1812->1812/udp, 18120/tcp   verify-freeradius
-bash-4.2#
-bash-4.2#
-bash-4.2#
-bash-4.2# service radiusd start
Redirecting to /bin/systemctl start radiusd.service
Job for radiusd.service failed because the control process exited with error code. See "systemctl status radiusd.service" and "journalctl -xe" for details.
-bash-4.2#
-bash-4.2#
-bash-4.2# service radiusd status
Redirecting to /bin/systemctl status radiusd.service
● radiusd.service - FreeRADIUS multi-protocol policy server
   Loaded: loaded (/usr/lib/systemd/system/radiusd.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2022-03-10 21:50:16 EET; 1s ago
     Docs: man:radiusd(8)
           man:radiusd.conf(5)
           http://wiki.freeradius.org/
           http://networkradius.com/doc/
  Process: 32696 ExecStartPre=/usr/sbin/radiusd $FREERADIUS_OPTIONS -Cx -lstdout (code=exited, status=1/FAILURE)

Mar 10 21:50:16 localhost.localdomain systemd[1]: Failed to start FreeRADIUS multi-protocol policy server.
Mar 10 21:50:16 localhost.localdomain systemd[1]: Unit radiusd.service entered failed state.
Mar 10 21:50:16 localhost.localdomain systemd[1]: radiusd.service failed.
-bash-4.2#
-bash-4.2#
-bash-4.2#

**Comment by jpereira** [comment]
@elie2282 Questions belongs to the freeradius-mailing list. Not here. Please take a look at https://wiki.freeradius.org/guide/Users-Mailing-List
